import React, { Component } from "react";


class Terms extends Component {
  render() {
    return (
      <div className="App">
<h1>Terms and Conditions</h1>
<p>Effective Date of Last Revision: April 1, 2018</p>
<p>This software application is controlled by Soma Labs LLC (referred to herein together with its affiliates as “The MeatStick”, "us", "we" or the "Company"). By creating a user account and/or accessing or using the associated software, products and/or devices (the “Services”), you represent and warrant that you have read, understand and agree to be bound by these Terms of Use and Privacy Policy (collectively, the "Terms of Use" or "Agreement”). We reserve the right, at our sole discretion, to change, modify, add, or delete portions of these Terms of Use at any time without further notice. If we do this, we will post the changes to these Terms of Use on this page and will indicate at the top of this page the date these terms were last revised. If you have a user account prior to any such changes, you will be prompted to review the revised Terms of Use, and accept them, prior to logging in to your user account. Your continued use of the Services after any such changes constitutes your acceptance of the new Terms of Use. If you do not agree to abide by these or any future Terms of Use, do not use or access (or continue to use or access) the Services. </p>
<h3>PLEASE READ THESE TERMS OF USE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.</h3> 
 
<h2>Commonly Used Terms and their Definitions</h2>
<p>All initial capitalized terms used in this Agreement shall have the meaning ascribed to such terms. In addition to the terms defined elsewhere in this Agreement, the following Terms shall have the meaning listed below: </p>
<ul>
<li>• “Content” includes all information downloaded, uploaded or appearing on the Services and which may become available for use or display, including without limitation all designs, text, graphics, pictures, video, animation, information, applications, software, programs, music, sound, audio, schematics, illustrations, diagrams, data, and other files and creative output, in whatever format. </li>
<li>• “Intellectual Property Rights” means any writing, trade name, trademark, service mark, mask work or any other material registered or otherwise protected or protectable under state, federal, or foreign patent, trademark, copyright, trade secret or similar laws.</li>
<li>• “Non-The MeatStick Product” means a product manufactured and/or controlled by a Person other than (a) The MeatStick and (b) a Person owned or controlled by The MeatStick.</li>
<li>• "Person" means any individual, trust or legal entity.</li>
<li>• “Personally Identifiable Information” means information that can be reasonably linked to a specific User.</li>
<li>• “Proprietary Information” includes any scientific, technical, trade or business secrets of any person or entity and any scientific, technical, trade or business materials that a person or entity treats, or is obligated to treat, as confidential or proprietary, including, but not limited to, Inventions belonging to a person or entity and confidential information obtained by or given to a person or entity about or belonging to a third party.</li>
<li>• “User” is anyone that creates an account and is registered to provide content on the Services and includes all other Persons who participate on the Services other than the Company.</li>
 </ul>

<h2>The MeatStick’s Control of the Services</h2>
<p>You acknowledge that The MeatStick is a service provider that generally does not regulate the content of Users' interactions with the Services. As a result, The MeatStick has very little control, if any, over the quality, safety, morality, legality, truthfulness or accuracy of User Content provided by Users. Nonetheless, The MeatStick reserves the right to monitor and/or limit any User Content provided by a User on the Services.</p>
<h2>Service Interruptions and Changes to the Services</h2>
<p>The MeatStick reserves the right to interrupt the Services with or without prior notice for any reason or no reason. You agree that The MeatStick will not be liable for any interruption of the Services, delay or failure to perform. The MeatStick has the right at any time for any reason or no reason to change and/or eliminate any aspect(s) of the Services as it sees fit in its sole discretion.</p>
<h2>Eligibility</h2>
<p>Participation in the Services is void where prohibited. The Services are intended solely for users who are thirteen (13) years of age or older. Any registration by, use of or access to the Services by anyone under 13 is unauthorized, unlicensed and in violation of these Terms of Use. By using the Services, you represent and warrant that you are 13 or older, and that you agree to and will abide by all of the terms and conditions of this Agreement. </p> 
<h2>Registration Data; Account Security</h2>
<p>In consideration of your use of the Services, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the Services ("Registration Data"); (b) maintain the security of your password and identification; (c) maintain and promptly update the Registration Data and any other information you provide to Company, and keep it accurate, current and complete; and (d) be fully responsible for all use of your account and for any actions that take place using your account.</p>
<h2>Proprietary Rights in Content; Limited License</h2>
<p>All Content is the proprietary property of the Company, its Users or other licensors, with all rights reserved. No Content may be modified, copied, distributed, reproduced, republished, downloaded, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without the Company's prior written permission, except that the foregoing does not apply to Content that is legally provided by Users on the Services, which is addressed in more detail in the section below titled “Ownership of Content.” Provided that you are eligible for use of the Services, you are granted a limited license to access and use the Services and the Content and to download or print a copy of any portion of the Content to which you have properly gained access solely for your own personal use, in connection with participating on the Services. Except for your own Content, you may not upload or republish Content on any Internet, Intranet or Extranet services or incorporate the information in any other database or compilation, and any use of the Content not explicitly permitted herein is strictly prohibited. The foregoing license is subject to these Terms of Use and does not include use of any data mining, robots or similar data gathering or extraction methods. Any use of the Services or the Content other than as specifically authorized herein, without the prior written permission of Company, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws including copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to Intellectual Property Rights, whether by estoppel, implication or otherwise. The foregoing license is revocable at any time by the Company without notice and with or without cause.</p>
<h2>Ownership of Content</h2>
<p>The Company and each User that is a party to this Agreement acknowledges and agrees that, subject to the terms and conditions of this Agreement, Users may retain any and all applicable Intellectual Property Rights with respect to any Content that a User creates or submits using the Services, to the extent such User has such rights under applicable law.</p>
<p>Notwithstanding the foregoing, you understand and agree that by submitting Content to any area of the Services, you automatically grant (and you represent and warrant that you have the right to grant) to the Company: (a) a royalty-free, worldwide, fully paid-up, perpetual, irrevocable, non-exclusive right and license to use, reproduce and distribute your Content within the Services, as permitted by you through your interactions on the Services, (b) the perpetual and irrevocable right to delete any or all of your Content from Company owned, controlled or used servers and from the Services, for any reason or no reason, whether intentional or unintentional, and, without any liability of any kind to you or any other party; and (c) a royalty-free, fully paid-up, perpetual, irrevocable, non-exclusive right and license to copy, analyze and use any of your Content as the Company may deem necessary or desirable for purposes of debugging, testing and/or providing support services in connection with the Services. </p>
<p>You further understand and agree that: (i) you are solely responsible for understanding all copyright, patent, trademark, trade secret and other intellectual property or other laws that may apply to your Content hereunder, including without limitation, any rights or obligations you may or may not have concerning Open Source Software; (ii) you are solely responsible for, and the Company will have no liability in connection with, the legal consequences of any actions or failures to act on your part while using the Services, including without limitation any legal consequences relating to your or any other Person’s Intellectual Property Rights or Proprietary Information; and (iii) The MeatStick’s acknowledgement hereunder of your Intellectual Property Rights in your Content does not constitute a legal opinion or legal advice, but is intended solely as an expression of the Company’s intention not to require Users of the Services to forego certain Intellectual Property Rights with respect to Content they submit to the Services, subject to the terms of this Agreement.</p>
<p>The MeatStick retains ownership of User account data, regardless of any Intellectual Property Rights in User provided Content.</p>
<p>You agree that even though you may retain certain copyright or other Intellectual Property Rights with respect to Content that is submitted on the Services, you do not own the account you use to access the Services, nor do you own any data The MeatStick stores on its servers (including without limitation any data representing or embodying any or all of your Content). Your Intellectual Property Rights in any Content, if any, do not confer any rights of access to the Services or any rights to data stored by or on behalf of the Company.</p>
<h2>Trademarks</h2>
<p>“The MeatStick”, names of The MeatStick-owned applications or software associated with the foregoing, and other associated graphics, logos, designs, page headers, button icons, scripts and service names are registered trademarks, trademarks or trade dress (collectively, the “Marks”) of The MeatStick in the U.S. and/or other countries. The Marks may not be used, including as part of trademarks and/or as part of domain names, in connection with any product or service in any manner that is likely to cause confusion or association or affiliation with The MeatStick and may not be copied, imitated, or used, in whole or in part, without the prior written permission of the Company.</p>
<h2>Conduct by Users; Prohibited Conduct</h2>
<p>You agree that you shall not: (i) take any action or upload, post, e-mail or otherwise transmit to or via the Services any Content that infringes or violates any third party rights, including without limitation all Intellectual Property Rights, or that constitutes any other Person’s Proprietary Information; (ii) impersonate any Person without their consent, including, but not limited to, a The MeatStick employee, or falsely state or otherwise misrepresent your affiliation with any Person; (iii) take any action or upload, post, e-mail or otherwise transmit to or via the Services any Content that violates any law or regulation; (iv) take any action or upload, post, e-mail or otherwise transmit to or via the Services any Content as determined by The MeatStick at its sole discretion that is harmful, threatening, abusive, harassing, causes tort, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; (v) take any actions or upload, post, e-mail or otherwise transmit to or via the Services any Content that contains any viruses, Trojan horses, worms, spyware, time bombs, cancel bots or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information; (vi) take any action or upload, post, email or otherwise transmit to or via the Services any Content that would violate any right or duty under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); (vii) upload, post, email or otherwise transmit to or via the Services any unsolicited or unauthorized advertising, or promotional materials, that are in the nature of "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation that the Company considers in its sole discretion to be of such nature; (viii) interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services; (ix) attempt to gain access to any other User’s account or password; or (x) "stalk", abuse or attempt to abuse, or otherwise harass another user; (xi) charge any third party for use of the Services; or (xii) modify, adapt, reverse engineer, decompile or attempt to discover the source code of the Services. Any violation by you of the terms of the foregoing may result in immediate and permanent suspension or cancellation of your account.</p>
 
<h2>Monitoring Content</h2>
<p>The MeatStick is not responsible or liable in any manner for any Content posted on the Services or in connection with the Services. We do not control and are not responsible for what Users post, transmit or share on the Services and are not responsible for any offensive, inappropriate, obscene, unlawful or otherwise objectionable User provided Content you may encounter on the Services. The Company is not responsible for the conduct, whether online or offline, of any User of the Services.</p>
<p>All Data on the Company’s Servers is subject to Deletion, Alteration or Transfer</p>
<p>When using the Services, you may accumulate Content, objects, items, scripts, or other value or status indicators that reside as data on the Company’s servers. THIS DATA, AND ANY OTHER DATA, ACCOUNT HISTORY AND ACCOUNT NAMES RESIDING ON The MeatStick’S SERVERS, MAY BE DELETED, ALTERED, MOVED OR TRANSFERRED AT ANY TIME FOR ANY REASON IN THE MEATSTICK’S SOLE DISCRETION. YOU ACKNOWLEDGE THAT, NOTWITHSTANDING ANY COPYRIGHT OR OTHER INTELLECTUAL PROPERTY RIGHTS YOU MAY HAVE WITH RESPECT TO CONTENT YOU PROVIDE ON THE SERVICES, AND NOTWITHSTANDING ANY VALUE ATTRIBUTED TO SUCH CONTENT OR OTHER DATA BY YOU OR ANY THIRD PARTY, The MeatStick DOES NOT PROVIDE OR GUARANTEE, AND EXPRESSLY DISCLAIMS (SUBJECT TO ANY UNDERLYING INTELLECTUAL PROPERTY RIGHTS IN THE CONTENT), ANY VALUE, CASH OR OTHERWISE, ATTRIBUTED TO ANY DATA RESIDING ON THE COMPANY’S SERVERS.</p>
 
<h3>YOU UNDERSTAND AND AGREE THAT THE MEATSTICK HAS THE RIGHT, BUT NOT THE OBLIGATION, TO REMOVE ANY CONTENT (INCLUDING YOUR CONTENT) IN WHOLE OR IN PART AT ANY TIME FOR ANY REASON OR NO REASON, WITH OR WITHOUT NOTICE AND WITHOUT ANY LIABILITY OF ANY KIND.</h3>
 
<h2>All Services are Provided "as is" Without Express or Implied Warranties</h2>
<p>THE MEATSTICK PROVIDES THE SERVICES STRICTLY ON AN "AS IS" BASIS, PROVIDED AND ACCEPTED AT YOUR OWN RISK, AND HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES OR CONDITIONS OF ANY KIND, WRITTEN OR ORAL, EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTY OF TITLE, NONINFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p>
<p>Without limiting the foregoing, the Company does not ensure continuous, error-free, secure or virus-free operation of the Services, the Services or your account, and you understand that you shall not be entitled to make any claim based on The MeatStick’s failure to provide any of the foregoing other than as explicitly provided in this Agreement. Some jurisdictions do not allow the disclaimer of implied warranties, and to that extent, the foregoing disclaimer may not apply to you. </p>
<p>The MeatStick’s liability to you is expressly limited, to the extent allowable under applicable law.</p>
<p>IN NO EVENT SHALL THE MEATSTICK OR ANY OF ITS SHAREHOLDERS, AFFILIATES, DIRECTORS, OFFICERS, SUBSIDIARIES, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION ANY DAMAGES FOR LOST PROFITS, ARISING (WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE) OUT OF OR IN CONNECTION WITH THE SERVICES (INCLUDING WITHOUT LIMITATION ITS MODIFICATION OR TERMINATION), YOUR ACCOUNT (INCLUDING WITHOUT LIMITATION ITS TERMINATION OR SUSPENSION) OR THIS AGREEMENT, WHETHER OR NOT THE COMPANY MAY HAVE BEEN ADVISED THAT ANY SUCH DAMAGES MIGHT OR COULD OCCUR AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY. IN ADDITION, IN NO EVENT WILL The THE MEATSTICK’S CUMULATIVE LIABILITY TO YOU FOR DIRECT DAMAGES OF ANY KIND OR NATURE EXCEED ONE HUNDRED DOLLARS (U.S. $100.00).</p>
<p>Some jurisdictions do not allow the foregoing limitations of liability, so to the extent that any such limitation is impermissible, such limitation may not apply to you. You agree that The MeatStick shall not be held responsible or liable for anything that occurs or results from accessing the Services or participating in the Services.</p>
<h2>Indemnification</h2>
<p>You hereby agree to defend, indemnify and hold harmless The MeatStick, its shareholders, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, licensees, distributors, successors and assigns and other Users of the Services, from all damages, liabilities, claims and expenses, including without limitation attorneys' fees and costs, arising from any breach of this Agreement by you, or from your use of the Services. You agree to defend, indemnify and hold harmless the Company, its shareholders, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, licensees, and distributors, successors and assigns from all damages, liabilities, claims and expenses, including without limitation attorneys' fees and costs, arising from any claims by third parties that your activity on the Services or your Content infringes upon, violates or misappropriates any of their Intellectual Property Rights or discloses their Proprietary Information.</p>
<h2>Non-The MeatStick Products</h2>
<p>The Services may enable your interaction with Non-The MeatStick Products. These Non-The MeatStick Products are outside The MeatStick’s control and not covered by this Agreement. The MeatStick makes no representations or warranties concerning such Non-The MeatStick Products, nor shall The MeatStick have any liability concerning such Non-The MeatStick Products. You should contact the manufacturer of such Non-The MeatStick Products for information regarding such Non-The MeatStick Products.</p>
 
<h1>Privacy Policy</h1>
<h2>COLLECTION AND USES OF YOUR PERSONAL INFORMATION</h2>
<p>You acknowledge and agree that The MeatStick, in its sole discretion, may track, record, observe or follow any and all of your interactions within the Services. Except as otherwise provided herein, the personal information you provide to us during registration is used for the Company’s internal purposes only. The MeatStick uses the information it collects to learn what you like and to improve the Services.</p>
<p>You are required to provide your full name, a valid email address and/or password during User registration that will represent your identity on the Services. In order to connect a device to your network you are may provide your wireless network information such as SSID and network password. </p>
<p>Associated devices connect to your network, phone and User account by receiving wireless signals that come from your mobile phone. During this process, certain types of technical information are transferred between your phone and the associated device, including your wireless network information such as SSID and network password, and technical and identifying information relating to your phone and the associated device. </p>
<p>You agree that The MeatStick may communicate with you via email and any similar technology for any purpose relating to the Services.</p>

           
      </div>
    );
  }
}

export default Terms;